version: '2'
services:
  dockerlab-db-service-java:
    build: ../part5
    depends_on:
        - dockerlab-mysql
    links:
        - dockerlab-mysql:db
    env_file: ../part5/dev.env.properties
    environment:
        - DB_PORT=tcp://db:3306
  dockerlab-mysql:
    build: ../part2
    ports:
          - "3306:3306"
    expose:
          - 3306
    volumes:
     - ../data:/var/lib/mysql